joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
    
arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
      - panda_finger_joint1
      - panda_finger_joint2
    constraints:
        goal_time: 0.6
        
        stopped_velocity_tolerance: 0.05
        joint_a1: {trajectory: 0.1, goal: 0.1}
        joint_a2: {trajectory: 0.1, goal: 0.1}
        joint_a3: {trajectory: 0.1, goal: 0.1}
        joint_a4: {trajectory: 0.1, goal: 0.1}
        joint_a5: {trajectory: 0.1, goal: 0.1}
        joint_a6: {trajectory: 0.1, goal: 0.1}
        
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
    
    # gains: 
    # example_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}


joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
    
    
# finger_1:
#     type: effort_controllers/JointVelocityController
#     joint: panda_finger_joint1
#     pid: {p: 100.0, i: 0.01, d: 10.0}
# finger_2:
#     type: effort_controllers/JointVelocityController
#     joint: panda_finger_joint2
#     pid: {p: 100.0, i: 0.01, d: 10.0}

