
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

joint1_controller:
    type: effort_controllers/JointPositionController
    joint: panda_joint1
    pid: {p: 40.0, i: 1, d: 60.0}
joint2_controller:
    type: effort_controllers/JointPositionController
    joint: panda_joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}
joint3_controller:
    type: effort_controllers/JointPositionController
    joint: panda_joint3
    pid: {p: 100.0, i: 1, d: 10.0}
joint4_controller:
    type: effort_controllers/JointPositionController
    joint: panda_joint4
    pid: {p: 100.0, i: 1, d: 10.0}
joint5_controller:
    type: effort_controllers/JointPositionController
    joint: panda_joint5
    pid: {p: 100.0, i: 0.01, d: 10.0}
joint6_controller:
    type: effort_controllers/JointPositionController
    joint: panda_joint6
    pid: {p: 100.0, i: 0.01, d: 10.0}
joint7_controller:
    type: effort_controllers/JointPositionController
    joint: panda_joint7
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
joint8_controller:
    type: effort_controllers/JointPositionController
    joint: panda_finger_joint1
    pid: {p: 100.0, i: 1.0, d: 20.0}

joint9_controller:
    type: effort_controllers/JointPositionController
    joint: panda_finger_joint2
    pid: {p: 100.0, i: 1.0, d: 20.0}